server:
  port: 4000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/
spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/user-service
    username: postgres
    password: mysecretpassword
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
